[target.x86_64-unknown-illumos]
# Use the main branch image which has the latest fixes for illumos toolchain
# The default tagged image doesn't properly include Rust/cargo
image = "ghcr.io/cross-rs/x86_64-unknown-illumos:main"

[target.x86_64-unknown-illumos.env]
passthrough = [
  "RANLIB=/usr/local/x86_64-unknown-illumos/bin/x86_64-unknown-illumos-ranlib",
]
