[target.x86_64-unknown-illumos.env]
passthrough = [
  "RANLIB=/usr/local/x86_64-unknown-illumos/bin/x86_64-unknown-illumos-ranlib",
]

# Use edge tag for Windows GNU to ensure cargo is available in the container
[target.x86_64-pc-windows-gnu]
image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:edge"
