[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = []
[target.x86_64-apple-darwin]
rustflags = []
[target.aarch64-apple-darwin]
rustflags = []
[target.x86_64-unknown-linux-musl]
rustflags = []
[target.aarch64-unknown-linux-musl]
rustflags = []
