[package]
name = "third-party"
version = "0.1.0"
edition = "2024"

[dependencies]
# must be kept in sync with sentry-log
sentry = { version = "=0.36.0", features = ["debug-images"] }

[features]
force-sentry-env-dev = []
